### PR TITLE
Basic ELO -> Distribution ELO

### PR DESCRIPTION
**Pull request by Firestorm-253**
- Removed Consistency -> migration needed!
- Renamed Confidence to Deviation (/Uncertanity in blazor) -> migration needed!

- Implement the new Algorithm and replace the old one
- some cleanups

(this obsiously also resulted in a fixed Confidence which is now the Deviation/Uncertanity)

### CODE REVIEW

**Comment by Firestorm-253** [comment]
@ipax77 i expected the checks to fail, we need to review the changes to make sure everything will work fine with the migrations and the way i replaced them. Especially with the removal of Consistency!

**Comment by ipax77** [comment]
Thank you for the PR! Are there any data available how the now rating would look like? Distribution, Highest or lowest rating ..?

**Comment by ipax77** [comment]
[FireMath.NET](https://github.com/ipax77/FireMath.NET) Is just a wrapper to MathNet.Numerics? Also the tests are not running for this package. If possible I don't want any unnecessary dependencies I cannot control.

**Comment by Firestorm-253** [comment]
> [FireMath.NET](https://github.com/ipax77/FireMath.NET) Is just a wrapper to MathNet.Numerics? Also the tests are not running for this package. If possible I don't want any unnecessary dependencies I cannot control.

I replaced it and included it manually into the project.

**Pull request merged**
