### PR TITLE
Mmr Adaptions

### PR DESCRIPTION
**Pull request by Firestorm-253**

### CODE REVIEW

**Comment by ipax77** [comment]
Previous conversations:

@ipax77 
I don't think we should have a negative rating ever. It is a psychological reason - someone with a negative rating will never willingly upload their replays.
The consistency thing needs some explanation - would it be possible to update the wiki page? E.g. if there will be a match making system or someone who plays mostly inhouse, their winrate will be around 50% which means no consistency?

@Firestorm-253 
We are currently doing a clip at 0.
So there would be pubs (for example trolls) who belong even lower, but we don’t let them.
If we have the start mmr at 1k, players with 2.5k for example will still lose a lot with a 0 mmr teammate.
Which is the opposite of what we want.
I wanna drown the very bad players as far as possible, to protect the players from trolls and absolute noobs.

**Comment by ipax77** [comment]
Problems:
- Computer Player still shows up in the ratings
  there might be a better solution than bringing all player-names into the calculation process
- Player Rating Charts for negative rated players is messed up
  we should add a hidden rating field to accomplish the negative ratings. On the website we should never show negative ratings to the users

**Comment by Firestorm-253** [comment]
- Computer Player done by @ipax77 outside of this PR. (reverted changes here)
- Player Rating Charts are not negative in my tests. pls send reconstruction settings and data or screenshots.

**Comment by ipax77** [comment]
Computer Players are fixed with #143

**Pull request merged**
