### PR TITLE
Bug fixes and cu

### PR DESCRIPTION
**Pull request by Firestorm-253**
- ReplayData.IsInvalid bugfix
- AddPlayersRankings() cu

### CODE REVIEW

**Comment by ipax77** [comment]
Removed const variables in foreach loop

**Comment by ipax77** [comment]
ReplayData -> IsInvalid is related to CommanderComboMmr, only? If so I would suggest to give it a related naming.
From a logical point of view: Shouldn't '!IsStd' and 'HasNoLeaver' be sufficient?

**Comment by ipax77** [comment]
ReplayData: IsStd fixed. Removed 2nd constructor

**Comment by ipax77** [comment]
We should consider referencing the ReplayDsRDto in the ReplayData so we don't have to copy properties.

**Comment by Firestorm-253** [comment]
@ipax77 
> We should consider referencing the ReplayDsRDto in the ReplayData so we don't have to copy properties.

i didn't do this on purpose in the past cause i wanted to have it independent in case of creating synthetic ReplayData without a real ReplayDsRDto.
With the newest talk we had about this, the 2nd Contructor can be removed aswell as alot can be linked as properties instead of copied as values. i will look over it again tomorrow.


> ReplayData -> IsInvalid is related to CommanderComboMmr, only? If so I would suggest to give it a related naming. From a logical point of view: Shouldn't '!IsStd' and 'HasNoLeaver' be sufficient?

in my mind it should be enough to cancel out everything (HasNoLeaver). but i need to take a closer look tomorrow, i doubt that we made something without a reason. 


gn8 ^^

**Comment by Firestorm-253** [comment]
image
i don't understand that, it's simply incorrect, no?

**Comment by Firestorm-253** [comment]
It is fixed and ready for implementation now.

I will do a rework of ratingType enum according to hex-flagging to better work with the TE / none-TE types.

**Pull request merged**
